"""
Encryption Manager Module

This module provides encryption utilities for securing sensitive data at rest.
Uses Fernet symmetric encryption (AES-128-CBC + HMAC) for secure token storage.

Classes:
    EncryptionManager: Manages encryption/decryption operations using Fernet

Usage:
    # With provided key
    manager = EncryptionManager("your_base64_encoded_key")
    encrypted = manager.encrypt("sensitive_data")
    decrypted = manager.decrypt(encrypted)
    
    # Auto-generate key
    manager = EncryptionManager.create_with_new_key()
    key = manager.get_key()  # Save this key securely!
"""

import logging
import base64
from typing import Optional
from cryptography.fernet import Fernet, InvalidToken

logger = logging.getLogger(__name__)


class EncryptionManager:
    """
    Manages encryption and decryption operations using Fernet symmetric encryption.
    
    Fernet provides authenticated encryption (AES-128-CBC + HMAC-SHA256) which ensures
    both confidentiality and integrity of encrypted data. This is the recommended
    approach for encrypting data at rest.
    
    Attributes:
        _fernet (Fernet): The Fernet cipher instance for encryption/decryption
        _key (bytes): The encryption key (kept for export purposes)
    
    Methods:
        encrypt(): Encrypt plaintext string to bytes
        decrypt(): Decrypt ciphertext bytes to string
        get_key(): Get the base64-encoded encryption key
        generate_key(): Static method to generate a new Fernet key
        create_with_new_key(): Class method to create manager with new key
    """
    
    def __init__(self, key: str):
        """
        Initialize the EncryptionManager with a Fernet key.
        
        Args:
            key (str): Base64-encoded Fernet encryption key (32 bytes when decoded)
                Must be a valid Fernet key generated by Fernet.generate_key()
                
        Raises:
            ValueError: If the key is invalid or has wrong format
            
        Example:
            >>> key = Fernet.generate_key().decode()
            >>> manager = EncryptionManager(key)
        """
        try:
            # Convert string key to bytes
            key_bytes = key.encode() if isinstance(key, str) else key
            
            # Validate key format by creating Fernet instance
            self._fernet = Fernet(key_bytes)
            self._key = key_bytes
            
            logger.info("EncryptionManager initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize EncryptionManager: {e}")
            raise ValueError(
                f"Invalid encryption key: {e}. "
                f"Key must be a base64-encoded Fernet key (32 bytes when decoded). "
                f"Generate a valid key with: EncryptionManager.generate_key()"
            )
    
    def encrypt(self, plaintext: str) -> bytes:
        """
        Encrypt a plaintext string using Fernet encryption.
        
        The encryption process:
        1. Converts string to bytes (UTF-8)
        2. Encrypts using Fernet (AES-128-CBC + HMAC)
        3. Returns base64-encoded ciphertext
        
        Args:
            plaintext (str): The plaintext string to encrypt
            
        Returns:
            bytes: Encrypted ciphertext (base64-encoded)
            
        Raises:
            Exception: If encryption fails
            
        Example:
            >>> manager = EncryptionManager(key)
            >>> encrypted = manager.encrypt("secret_token_12345")
            >>> print(type(encrypted))  # <class 'bytes'>
        """
        try:
            plaintext_bytes = plaintext.encode('utf-8')
            ciphertext = self._fernet.encrypt(plaintext_bytes)
            
            logger.debug(
                f"Encrypted data: plaintext_length={len(plaintext)}, "
                f"ciphertext_length={len(ciphertext)}"
            )
            
            return ciphertext
        except Exception as e:
            logger.error(f"Encryption failed: {e}")
            raise
    
    def decrypt(self, ciphertext: bytes) -> str:
        """
        Decrypt ciphertext bytes back to a plaintext string.
        
        The decryption process:
        1. Verifies HMAC to ensure data integrity
        2. Decrypts using Fernet (AES-128-CBC)
        3. Converts bytes back to string (UTF-8)
        
        Args:
            ciphertext (bytes): The encrypted data to decrypt
            
        Returns:
            str: Decrypted plaintext string
            
        Raises:
            InvalidToken: If ciphertext is corrupted or key is wrong
            Exception: If decryption fails for other reasons
            
        Example:
            >>> manager = EncryptionManager(key)
            >>> encrypted = manager.encrypt("secret_token")
            >>> decrypted = manager.decrypt(encrypted)
            >>> print(decrypted)  # "secret_token"
        """
        try:
            plaintext_bytes = self._fernet.decrypt(ciphertext)
            plaintext = plaintext_bytes.decode('utf-8')
            
            logger.debug(
                f"Decrypted data: ciphertext_length={len(ciphertext)}, "
                f"plaintext_length={len(plaintext)}"
            )
            
            return plaintext
        except InvalidToken as e:
            logger.error(
                f"Decryption failed: Invalid token or wrong key. "
                f"The data may be corrupted or encrypted with a different key."
            )
            raise
        except Exception as e:
            logger.error(f"Decryption failed: {e}")
            raise
    
    def get_key(self) -> str:
        """
        Get the base64-encoded encryption key as a string.
        
        This key should be stored securely (e.g., in environment variables)
        and backed up. Losing the key means losing access to all encrypted data.
        
        Returns:
            str: Base64-encoded encryption key
            
        Example:
            >>> manager = EncryptionManager.create_with_new_key()
            >>> key = manager.get_key()
            >>> print(f"Save this key: {key}")
        """
        return self._key.decode('utf-8')
    
    @staticmethod
    def generate_key() -> str:
        """
        Generate a new Fernet encryption key.
        
        This is a static utility method that generates a cryptographically
        secure random key suitable for Fernet encryption. The key is
        base64-encoded and ready to use.
        
        Returns:
            str: Base64-encoded Fernet key (32 bytes when decoded)
            
        Example:
            >>> key = EncryptionManager.generate_key()
            >>> print(f"Generated key: {key}")
            >>> manager = EncryptionManager(key)
        """
        key = Fernet.generate_key()
        logger.info("Generated new Fernet encryption key")
        return key.decode('utf-8')
    
    @classmethod
    def create_with_new_key(cls) -> 'EncryptionManager':
        """
        Create an EncryptionManager with a newly generated key.
        
        Convenience method for creating a manager without manually
        generating a key first. The generated key can be retrieved
        with get_key() and should be saved for future use.
        
        Returns:
            EncryptionManager: New instance with a fresh encryption key
            
        Example:
            >>> manager = EncryptionManager.create_with_new_key()
            >>> key = manager.get_key()
            >>> # Save key to environment variable or secure storage
        """
        key = cls.generate_key()
        logger.info("Created EncryptionManager with new key")
        return cls(key)
    
    def verify_key(self) -> bool:
        """
        Verify that the encryption key is valid by performing a test encryption/decryption.
        
        Returns:
            bool: True if key is valid, False otherwise
            
        Example:
            >>> manager = EncryptionManager(key)
            >>> if manager.verify_key():
            ...     print("Key is valid")
        """
        try:
            test_data = "test_encryption_verification"
            encrypted = self.encrypt(test_data)
            decrypted = self.decrypt(encrypted)
            return decrypted == test_data
        except Exception as e:
            logger.error(f"Key verification failed: {e}")
            return False
